arch:
  ArraysPerMat: 1
  MatsPerBank: 1
  Merge: best
  SubarraysPerArray: 4
array:
  bit: 3
  cell: Numerical
  col: 32
  row: 32
  sensing: best
  sensingLimit: 0
  useEVACAMCost: false
cell:
  design: 6T2M
  device: Numerical
  maxConductance: 150
  minConductance: 0
  representation: voltage
  type: MCAM
  writeNoise:
    cellDesign: 6T2M
    device: Numerical
    hasWriteNoise: true
    maxConductance: 150
    minConductance: 0
    noiseType:
    - variation
    variation:
      stdDev: 0
      type: gaussian
query:
  FuncSim: false
  PerfEval: true
  bit: 3
  distance: euclidean
  parameter: 1
  searchScheme: knn
