arch:
  ArraysPerMat: 4
  MatsPerBank: 4
  Merge: exact
  SubarraysPerArray: 1
array:
  bit: 2
  cell: Numerical
  col: 32
  row: 32
  sensing: best
  sensingLimit: 0
cell:
  design: 6T2M
  device: Numerical
  maxConductance: 150
  minConductance: 0
  representation: voltage
  type: MCAM
  writeNoise:
    cellDesign: 6T2M
    device: Numerical
    hasWriteNoise: false
    maxConductance: 150
    minConductance: 0
    noiseType:
    - variation
    variation:
      stdDev: 0
      type: gaussian
query:
  FuncSim: 1
  PerfEval: true
  bit: 2
  distance: euclidean
  parameter: 1
  searchScheme: knn
